apiVersion: v1
kind: List
metadata: {}
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: sinatra-depl
    spec:
      replicas: 1
      strategy:
        type: Recreate
      selector:
        matchLabels:
          app: sinatra-app
      template:
        metadata:
          labels:
            app: sinatra-app
        spec:
          containers:
            - name: sinatra
              image: kuntao/sinatra_on_docker
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  memory: 256M
                  cpu: 1
              ports:
                - name: tcp
                  protocol: TCP
                  containerPort: 80
  - apiVersion: v1
    kind: Service
    metadata:
      name: sinatra-svc
    spec:
      type: NodePort
      selector:
        app: sinatra-app
      ports:
        - name: http
          protocol: TCP
          port: 8080
          targetPort: 80
          nodePort: 30080
  - apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: sinatra-ingress
    spec:
      rules:
        - host: sinatra.local
          http:
            paths:
              - path: /
                backend:
                  serviceName: sinatra-svc
                  servicePort: 8080
